"""Build fact-bound rewrite comparisons for the 10-story lounge test batch."""
import json
from pathlib import Path

SOURCE = Path(__file__).with_name("lounge_diverse_remainder.json")
OUT = Path(__file__).with_name("lounge_diverse_rewrite_review.json")

VOICES = {
 "Rook Danner": (["Dock Three is waiting on a lift that is not available.","The loader schedule is upside down today.","Everything ordinary on Dock Three is waiting its turn."], ["The cargo lift is reserved for emergency medical supplies, so ordinary loading has to wait.","Emergency medical supplies have the cargo lift. That is why the ordinary freight is standing still."], ["Nobody likes the delay, but medical cargo gets the lift first.","It is only one lift, and today it has a more urgent job."]),
 "Sana Rell": (["That survey crew has treated the quiet booth like a bunker.","The survey crew has been nursing the same drinks and saying almost nothing.","Everybody has noticed the survey crew pretending not to be noticed."], ["They are a visiting survey crew, and they will not say what they found.","All I know is that they found something worth keeping quiet about. They have not told the lounge what it was."], ["If they want it private, I let them keep their booth and their mystery.","People fill silence with nonsense. I would wait for something real."]),
 "Jenna Kross": (["The maintenance bay is full of ships that should not all be here at once.","I have been replacing the same little part all shift.","Every open bay has a ship waiting on the same repair."], ["A bad batch of maneuvering thruster seals reached the station, so several ships need replacements.","Those ships are here because their maneuvering thruster seals came from a bad batch and need replacing."], ["Small part, large inconvenience. That is repairs for you.","The seals are not glamorous, but neither is drifting sideways into a dock."]),
 "Ivet Marr": (["One container has managed to collect two cargo tags.","The paperwork is disagreeing with itself again.","That crate is innocent. Its records are the problem."], ["Two cargo tags were assigned to the same container, so inspection is reconciling the records.","The system attached two tags to one container. We have to determine which record is valid before it moves."], ["It is dull work until the wrong crate goes somewhere it should not.","Once the records agree, the argument ends and the crate moves."]),
 "Marek Vale": (["That freighter has reached the dock; it just cannot finish the last part alone.","The ship outside is waiting on a person, not a part.","One sick tug pilot can make a perfectly good schedule useless."], ["Its tug pilot called in sick, so the freighter has no docking escort yet.","The freighter is waiting because the tug pilot who should escort it into the dock called in sick."], ["It will move as soon as someone can take the escort job.","Nothing dramatic. It simply needs an escort before it comes in."]),
 "Lio Sable": (["The public relay is fine. The private side is taking the long route today.","Public calls are working; private messages are the ones taking their time.","The comms array is being serviced, and private traffic feels it first."], ["The public comms relay is working, but private-channel traffic is delayed while the relay array is serviced.","Private messages are delayed because the array is being serviced. Public traffic is still running."], ["Annoying, not mysterious. Give the technicians their window.","Your message is not lost; it is just waiting its turn."]),
 "Tamsin Roe": (["That crew is unloading a delivery they already finished delivering.","A rejected seal can turn one clean job into two.","The buyer sent a whole delivery back over one mismatch."], ["The buyer rejected the delivery because its cargo seal did not match the manifest, so the crew must return it.","The cargo seal and manifest do not match, so the buyer rejected it and the crew has to take it back."], ["Nobody gets paid extra for the return trip, which is why they look thrilled.","The paperwork may be small, but it can still send a ship back the way it came."]),
 "Perrin Holt": (["Tonight's menu is making stored food look ambitious.","Fresh produce missed the galley, and everyone has noticed.","The kitchen is working with what it has, which is not much fresh."], ["The galley received no fresh produce shipment, so tonight's menu is limited to stored food.","No fresh produce arrived, so dinner is made from stored food tonight."], ["I can make it filling. I did not promise it would inspire poetry.","Eat it while it is hot and call it character building."]),
 "Vera Nix": (["Vera made a perfectly ordinary sale into lounge entertainment.","Someone sold a useful part before checking what it was worth.","The lesson today is to look up a part before you price it."], ["Vera sold a useful part cheaply without checking its value, and the lounge is teasing her about it.","She sold a useful part for less than it was worth because she did not check its value first."], ["She will live. Her pride may need a few shifts in dry dock.","Everyone gets one bad sale. Hers just came with an audience."]),
 "Olan Pike": (["The closed corridor is less exciting than it looks.","Visitors are being redirected around a small repair job.","That handrail has more authority than most people expect today."], ["Visitors must use the marked corridor because a deckhand is repairing a damaged handrail nearby.","A deckhand is repairing a damaged handrail, so visitors are being routed through the marked corridor."], ["Follow the arrows and nobody has to make this a security incident.","It is a short detour, not a lockdown."]),
}

def main():
    items=[]
    for n, raw in enumerate(json.loads(SOURCE.read_text(encoding="utf-8"))["items"]):
        openers, answers, closes = VOICES[raw["contact_name"]]
        variant=n//10
        items.append({"id":raw["id"],"contact_name":raw["contact_name"],"contact_role":raw["contact_role"],"station":raw["station"],"allowed_facts":raw["allowed_facts"],"player_question":raw["player_question"],"original":{"opener":raw["opener"],"answer":raw["npc_answer"],"close":raw["close"]},"assistant_rewrite":{"opener":openers[variant%len(openers)],"answer":answers[variant%len(answers)],"close":closes[variant%len(closes)]},"review_reason":"Compared against the supplied fact packet for natural conversation, directness, and invented details.","status":"needs_user_confirmation"})
    OUT.write_text(json.dumps({"batch_id":"lounge-diverse-rewrite-review","items":items},indent=2),encoding="utf-8")
    print(f"Prepared {len(items)} varied rewrite comparisons")
if __name__=="__main__": main()
