"""Export the researched beats to the game's data directory.

Hand-transcribing twelve beats into JSON would introduce exactly the kind of
authored-text defect this project keeps tripping over (a stray hyphen, a
"he" in a packet). Generating it keeps the shipped data identical to what
was measured.

  python export_beats.py
"""
import io
import json
import os

import beat_transit
import beats_kaelen
import beats_nova
import demo_pool_v9
import nova_demos

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
OUT = os.path.join(ROOT, "data", "content", "quiet_moment_beats.json")


def unescape(text):
    """Python format-strings escape braces as {{ }}; GDScript does not.
    Left in place these reach the model as literal doubled braces."""
    return text.replace("{{", "{").replace("}}", "}")


def demo_block(pool):
    return [{"shape": s, "facts": f, "line": l} for s, f, l in pool]


def export_beat(bid, b):
    out = {
        "id": bid,
        "speaker": b.get("speaker", ""),
        "word_cap": b.get("cap", 28),
        "fire_probability": b.get("fire_probability", 1.0),
        "who": b["who"],
        "register": b["register"],
        "scope": b["scope"],
        "valence": b["valence"],
        "packets": b["packets"],
    }
    for key in ("lead_in_pool", "detail_pool", "detail_prompt"):
        if b.get(key):
            out[key] = b[key]
    return out


def main():
    beats = {}
    for src in (beats_kaelen.BEATS, beats_nova.BEATS):
        for bid, b in src.items():
            if bid == "nova_long_transit":
                continue          # superseded by the two-device transit beat
            beats[bid] = export_beat(bid, b)

    # transit is structurally different: two devices, its own vocabularies
    beats["nova_long_transit"] = {
        "id": "nova_long_transit",
        "speaker": "nova",
        "word_cap": beat_transit.CAP,
        "fire_probability": 1.0,
        "who": beat_transit.NOVA_WHO,
        "register": beat_transit.NOVA_REGISTER,
        "packets": beat_transit.PACKETS,
        "lead_in_pool": beat_transit.LEAD_INS,
        "devices": {
            "dangle": {"template": unescape(beat_transit.DANGLE),
                       "detail_pool": beat_transit.DETAILS},
            "jealousy": {"template": unescape(beat_transit.JEALOUSY),
                         "mechanics": beat_transit.MECHANICS,
                         "tools": beat_transit.TOOLS,
                         "parts": beat_transit.PARTS,
                         "mishaps": beat_transit.MISHAPS},
        },
    }

    doc = {
        "schema_version": 1,
        "document_type": "quiet_moment_beats",
        "note": ("Generated by docs/research/quiet_moment/export_beats.py. "
                 "Method and rationale: skills/skill_llm_character_dialogue.md"),
        "demo_pools": {
            "kaelen": demo_block(demo_pool_v9.KAELEN),
            "nova": demo_block(nova_demos.NOVA),
        },
        "beats": beats,
    }
    io.open(OUT, "w", encoding="utf-8").write(
        json.dumps(doc, indent="\t", ensure_ascii=False))
    print(f"wrote {OUT}")
    print(f"  {len(beats)} beats, "
          f"{sum(len(v) for v in doc['demo_pools'].values())} demos")
    for bid, b in sorted(beats.items()):
        extras = [k for k in ("lead_in_pool", "detail_pool", "devices") if k in b]
        print(f"  {bid:34s} packets={len(b['packets']):2d} "
              f"p={b['fire_probability']} {extras}")


if __name__ == "__main__":
    main()
