class_name NarrativeDirector
extends RefCounted

const CampaignBibleStoreType := preload(
	"res://scripts/persistence/CampaignBibleStore.gd"
)
const DomainJsonType := preload("res://scripts/domain/DomainJson.gd")
const ValidationResultType := preload(
	"res://scripts/domain/ValidationResult.gd"
)


static func build_campaign_bible_prompt(
	baseline_bible: Dictionary,
	idea_memory_context: String = ""
) -> String:
	var campaign_seed := str(baseline_bible.get("campaign_seed", ""))
	var idea_block := "No prior idea memory yet."
	if not idea_memory_context.strip_edges().is_empty():
		idea_block = idea_memory_context.strip_edges()
	return "\n".join([
		"You are the large local story model for a procedural space game.",
		"Create the campaign bible for one new campaign.",
		"",
		"Hard constraints:",
		"- Keep the handcrafted first system anchored by Zenith, Aurelia, and Vanguard.",
		"- Do not reveal future frontier factions to the player up front.",
		"- Kaelen is the only fixed recurring NPC besides the player.",
		"- Kaelen cannot die and her full mystery must never be completely solved.",
		"- New systems should reveal new factions, conflicts, ores, upgrades, rumors, and ships through gate travel.",
		"- Use dry, slightly dark PG-13 humor. Avoid repeating example jokes or catchphrases.",
		"- Rumors should include at least one trail that can eventually lead to a hidden discovery or endgame easter egg.",
		"- If story extends later, append a new horizon. Do not retcon known player choices.",
		"",
		"Campaign seed: %s" % campaign_seed,
		"",
		"Existing idea memory:",
		idea_block,
		"",
		"Return only JSON. No markdown. No comments.",
		"Required object fields:",
		"{",
		"  \"tone\": string,",
		"  \"core_pressure\": string,",
		"  \"kaelen_rule\": string,",
		"  \"faction_reveal_rule\": string,",
		"  \"humor_rule\": string,",
		"  \"address_rule\": string,",
		"  \"fallback_rule\": string,",
		"  \"story_horizon_rule\": string,",
		"  \"story_arcs\": [{\"name\": string, \"summary\": string}],",
		"  \"rumor_trails\": [{\"name\": string, \"clue_count\": number, \"payoff\": string}],",
		"  \"regeneration_triggers\": [{\"id\": string, \"description\": string}],",
		"  \"expansion_rules\": [string],",
		"  \"banned_repeats\": [string]",
		"}",
	])


static func parse_campaign_bible_response(
	envelope_text: String,
	baseline_bible: Dictionary,
	model_name: String
) -> Dictionary:
	var envelope := DomainJsonType.parse_object(envelope_text, "campaign_bible_envelope")
	var envelope_validation := envelope["validation"] as ValidationResult
	if not envelope_validation.is_valid():
		return _failure("response_envelope_parse_failed", envelope_validation)
	var envelope_data: Dictionary = envelope["data"]
	if not envelope_data.has("response"):
		var missing_response := ValidationResultType.new()
		missing_response.add_error(
			"response_envelope_missing_response",
			"Ollama response envelope did not include a response field."
		)
		return _failure("response_envelope_missing_response", missing_response)
	var response_text := str(envelope_data.get("response", "")).strip_edges()
	var parsed := DomainJsonType.parse_object(response_text, "campaign_bible_response")
	var response_validation := parsed["validation"] as ValidationResult
	if not response_validation.is_valid():
		return _failure("response_json_parse_failed", response_validation)
	var generated_validation := _validate_campaign_bible_shape(parsed["data"])
	if not generated_validation.is_valid():
		return _failure("campaign_bible_validation_failed", generated_validation)
	var bible := _normalized_campaign_bible(
		parsed["data"],
		baseline_bible,
		model_name
	)
	var validation := _validate_campaign_bible_shape(bible)
	if not validation.is_valid():
		return _failure("campaign_bible_validation_failed", validation)
	return {"ok": true, "bible": bible}


static func _normalized_campaign_bible(
	generated: Dictionary,
	baseline: Dictionary,
	model_name: String
) -> Dictionary:
	var bible := baseline.duplicate(true)
	for field in [
		"tone",
		"core_pressure",
		"kaelen_rule",
		"faction_reveal_rule",
		"humor_rule",
		"address_rule",
		"fallback_rule",
		"story_horizon_rule",
		"story_arcs",
		"rumor_trails",
		"regeneration_triggers",
		"expansion_rules",
		"banned_repeats",
	]:
		if generated.has(field):
			bible[field] = generated[field]
	bible["source"] = "llm"
	bible["generation_status"] = CampaignBibleStoreType.STATUS_LLM_GENERATED
	bible["source_model"] = model_name.strip_edges()
	bible["generation_note"] = "Campaign bible generated by the large-story local model."
	bible["last_generation_error"] = ""
	return bible


static func _validate_campaign_bible_shape(bible: Dictionary) -> ValidationResult:
	var result := ValidationResultType.new()
	for field in [
		"tone",
		"core_pressure",
		"kaelen_rule",
		"faction_reveal_rule",
		"humor_rule",
		"address_rule",
		"fallback_rule",
		"story_horizon_rule",
	]:
		if str(bible.get(field, "")).strip_edges().is_empty():
			result.add_error(
				"missing_campaign_bible_field",
				"Generated campaign bible field '%s' cannot be empty." % field,
				field
			)
	for array_field in [
		"story_arcs",
		"rumor_trails",
		"regeneration_triggers",
		"expansion_rules",
		"banned_repeats",
	]:
		if not bible.get(array_field, []) is Array:
			result.add_error(
				"invalid_campaign_bible_array",
				"Generated campaign bible field '%s' must be an array." % array_field,
				array_field
			)
	return result


static func _failure(reason: String, validation: ValidationResult) -> Dictionary:
	return {
		"ok": false,
		"reason": reason,
		"validation": validation,
	}
